services:
    file_locator:
        class: Symfony\Component\Config\FileLocator
        arguments:
            - ['%application.directory%']

    # configuration loading
    configuration_loader:
        class: Strider2038\ImgCache\Configuration\ConfigurationLoader
        arguments:
            - '@configuration_file_parser'
            - '@configuration_processor'
            - '@configuration_factory'

    configuration_file_parser:
        class: Strider2038\ImgCache\Utility\YamlFileParser
        arguments:
            - '@file_locator'

    configuration_processor:
        class: Symfony\Component\Config\Definition\Processor

    configuration_factory:
        class: Strider2038\ImgCache\Configuration\ConfigurationFactory
        arguments:
            - '@image_source_factory'

    image_source_factory:
        class: Strider2038\ImgCache\Configuration\ImageSource\ImageSourceFactory
        arguments:
            - '@entity_validator'

    # configuration setting
    configuration_setter:
        class: Strider2038\ImgCache\Configuration\ConfigurationSetter
        arguments:
            - '@request'
            - '@image_source_injector_factory'

    image_source_injector_factory:
        class: Strider2038\ImgCache\Configuration\Injection\ImageSourceInjectorFactory
