services:
    filesystem_image_storage_factory:
        class: Strider2038\ImgCache\Imaging\FilesystemImageStorageFactory
        arguments:
            - '@filesystem_storage_driver_factory'
            - '@entity_validator'
            - '@image_factory'
            - '@thumbnail_image_creator'

    filesystem_storage_driver_factory:
        class: Strider2038\ImgCache\Imaging\Storage\Driver\FilesystemStorageDriverFactory
        arguments:
            - '@file_operations'
            - '@guzzle_client_factory'
            - '@metadata_reader'
