parameters:
    geo_map_parsing_patterns:
        - '/(?P<type>(roadmap|satellite|hybrid|terrain))$/'
        - '/^(c|center)(?P<latitude>[-+]?[0-9]*\.?[0-9]+),(?P<longitude>[-+]?[0-9]*\.?[0-9]+)$/'
        - '/^(z|zoom)(?P<zoom>[0-9]+)$/'
        - '/^(s|size)(?P<width>[0-9]+)x(?P<height>[0-9]+)$/'
        - '/^(sc|scale)(?P<scale>[0-9]*\.?[0-9]+)$/'

services:
    geo_map_image_storage_factory:
        class: Strider2038\ImgCache\Imaging\GeoMapImageStorageFactory
        arguments:
            - '@geo_map_parameters_parser'
            - '@entity_validator'
            - '@image_factory'
            - '@guzzle_client_factory'

    geo_map_parsing_patterns:
        class: Strider2038\ImgCache\Collection\StringList
        arguments:
            - '%geo_map_parsing_patterns%'

    geo_map_parameters_factory:
        class: Strider2038\ImgCache\Imaging\Parsing\GeoMap\GeoMapParametersFactory

    geo_map_parameters_parser:
        class: Strider2038\ImgCache\Imaging\Parsing\GeoMap\GeoMapParametersParser
        arguments:
            - '@geo_map_parsing_patterns'
            - '@string_parameters_parser'
            - '@geo_map_parameters_factory'
            - '@entity_validator'
