parameters:
    image_parameters.quality: 90
    transformation_factory_map:
        /^(s|size)(?P<parameters>\d.*)$/: '@resizing_transformation_factory'
        /^(r|rotate)(?P<parameters>-?\d.*)$/: '@rotating_transformation_factory'
        /^(s|shift)(?P<parameters>(x|y).*)$/: '@shifting_transformation_factory'
        /^flip$/: '@flip_transformation_factory'
        /^flop$/: '@flop_transformation_factory'

services:
    # dependency management
    image_storage_factory:
        class: Strider2038\ImgCache\Imaging\ImageStorageFactory
        arguments:
            - '@filesystem_image_storage_factory'
            - '@geo_map_image_storage_factory'

    image_cache_factory:
        class: Strider2038\ImgCache\Imaging\ImageCacheFactory
        arguments:
            - '@file_operations'
            - '@image_processor'

    # imaging/extraction
    thumbnail_image_creator:
        class: Strider2038\ImgCache\Imaging\Extraction\ThumbnailImageCreator
        arguments:
            - '@thumbnail_processing_configuration_parser'
            - '@image_processor'

    # imaging/naming
    directory_name_factory:
        class: Strider2038\ImgCache\Imaging\Naming\DirectoryNameFactory
        arguments:
            - '@entity_validator'
            - '@file_operations'
    image_filename_factory:
        class: Strider2038\ImgCache\Imaging\Naming\ImageFilenameFactory
        arguments:
            - '@entity_validator'

    # imaging/image
    image_factory:
        class: Strider2038\ImgCache\Imaging\Image\ImageFactory
        arguments:
            - '@image_parameters_factory'
            - '@entity_validator'

    # imaging/parsing
    thumbnail_filename_parser:
        class: Strider2038\ImgCache\Imaging\Parsing\Filename\ThumbnailFilenameParser
        arguments:
            - '@entity_validator'
    thumbnail_processing_configuration_parser:
        class: Strider2038\ImgCache\Imaging\Parsing\Processing\ThumbnailProcessingConfigurationParser
        arguments:
            - '@transformation_creator'
            - '@image_parameters_factory'
            - '@image_parameters_modifier'
    string_parameters_parser:
        class: Strider2038\ImgCache\Imaging\Parsing\StringParametersParser

    # imaging/processing
    image_parameters_factory:
        class: Strider2038\ImgCache\Imaging\Image\ImageParametersFactory
        arguments:
            - '%image_parameters.quality%'
    image_parameters_modifier:
        class: Strider2038\ImgCache\Imaging\Parsing\ImageParametersModifier
        arguments:
            - '@string_parameters_parser'
    image_processor:
        class: Strider2038\ImgCache\Imaging\Processing\ImageProcessor
        arguments:
            - '@imagick_transformer_factory'
            - '@image_factory'
        calls:
            - [setLogger, ['@logger']]
    imagick_transformer_factory:
        class: Strider2038\ImgCache\Imaging\Processing\Imagick\ImagickTransformerFactory
        arguments:
            - '@file_operations'
            - '@stream_factory'

    # imaging/transformation
    transformation_creator:
        class: Strider2038\ImgCache\Imaging\Processing\Transforming\TransformationCreator
        arguments:
            - '@transformation_factory_map'

    transformation_factory_map:
        class: Strider2038\ImgCache\Imaging\Processing\Transforming\TransformationFactoryMap
        arguments:
            - '%transformation_factory_map%'

    resizing_transformation_factory:
        class: Strider2038\ImgCache\Imaging\Processing\Transforming\ResizingTransformationFactory
        arguments:
            - '@string_parameters_parser'
            - '@entity_validator'
    rotating_transformation_factory:
        class: Strider2038\ImgCache\Imaging\Processing\Transforming\RotatingTransformationFactory
        arguments:
            - '@string_parameters_parser'
            - '@entity_validator'
    shifting_transformation_factory:
        class: Strider2038\ImgCache\Imaging\Processing\Transforming\ShiftingTransformationFactory
        arguments:
            - '@string_parameters_parser'
    flip_transformation_factory:
        class: Strider2038\ImgCache\Imaging\Processing\Transforming\FlipTransformationFactory
    flop_transformation_factory:
        class: Strider2038\ImgCache\Imaging\Processing\Transforming\FlopTransformationFactory
