parameters:
    image_parameters.quality: 90

services:
    # imaging/extraction
    thumbnail_image_creator:
        class: Strider2038\ImgCache\Imaging\Extraction\ThumbnailImageCreator
        arguments:
            - '@thumbnail_processing_configuration_parser'
            - '@image_processor'

    # imaging/naming
    directory_name_factory:
        class: Strider2038\ImgCache\Imaging\Naming\DirectoryNameFactory
        arguments:
            - '@entity_validator'
            - '@file_operations'
    image_filename_factory:
        class: Strider2038\ImgCache\Imaging\Naming\ImageFilenameFactory
        arguments:
            - '@entity_validator'

    # imaging/image
    image_factory:
        class: Strider2038\ImgCache\Imaging\Image\ImageFactory
        arguments:
            - '@image_parameters_factory'
            - '@entity_validator'

    # imaging/parsing
    thumbnail_filename_parser:
        class: Strider2038\ImgCache\Imaging\Parsing\Filename\ThumbnailFilenameParser
        arguments:
            - '@entity_validator'
    thumbnail_processing_configuration_parser:
        class: Strider2038\ImgCache\Imaging\Parsing\Processing\ThumbnailProcessingConfigurationParser
        arguments:
            - '@transformations_creator'
            - '@image_parameters_factory'
            - '@image_parameters_configurator'

    # imaging/processing
    image_parameters_factory:
        class: Strider2038\ImgCache\Imaging\Image\ImageParametersFactory
        arguments:
            - '%image_parameters.quality%'
    image_parameters_configurator:
        class: Strider2038\ImgCache\Imaging\Parsing\ImageParametersConfigurator
    image_processor:
        class: Strider2038\ImgCache\Imaging\Processing\ImageProcessor
        arguments:
            - '@imagick_transformer_factory'
            - '@image_factory'
        calls:
            - [setLogger, ['@logger']]
    imagick_transformer_factory:
        class: Strider2038\ImgCache\Imaging\Processing\Imagick\ImagickTransformerFactory
        arguments:
            - '@file_operations'
            - '@stream_factory'

    # imaging/transformation
    transformations_creator:
        class: Strider2038\ImgCache\Imaging\Transformation\TransformationCreator
        arguments:
            - '@transformation_factory_flyweight'
    transformation_factory_flyweight:
        class: Strider2038\ImgCache\Imaging\Transformation\TransformationFactoryFlyweight

    # imaging/source
    storage_filename_factory:
        class: Strider2038\ImgCache\Imaging\Storage\Data\StorageFilenameFactory

