services:
    image_cache:
        class: Strider2038\ImgCache\Imaging\ImageCache
        arguments:
            - '@cache_directory_proxy'
            - '@file_operations'
            - '@image_processor'

    cache_directory_proxy:
        synthetic: true
