parameters:
    save_options.quality: 90

services:
    # imaging/naming
    directory_name_factory:
        class: Strider2038\ImgCache\Imaging\Naming\DirectoryNameFactory
        arguments:
            - '@entity_validator'
            - '@violations_formatter'
            - '@file_operations'
    image_filename_factory:
        class: Strider2038\ImgCache\Imaging\Naming\ImageFilenameFactory
        arguments:
            - '@entity_validator'
            - '@violations_formatter'

    # imaging/image
    image_factory:
        class: Strider2038\ImgCache\Imaging\Image\ImageFactory
        arguments:
            - '@save_options_factory'
            - '@image_validator'
            - '@file_operations'
            - '@stream_factory'

    # imaging/parsing
    thumbnail_filename_parser:
        class: Strider2038\ImgCache\Imaging\Parsing\Filename\ThumbnailFilenameParser
        arguments:
            - '@key_validator'
            - '@image_validator'
            - '@thumbnail_processing_configuration_parser'
    thumbnail_processing_configuration_parser:
        class: Strider2038\ImgCache\Imaging\Parsing\Processing\ThumbnailProcessingConfigurationParser
        arguments:
            - '@transformations_creator'
            - '@save_options_factory'
            - '@save_options_configurator'

    # imaging/processing
    save_options_factory:
        class: Strider2038\ImgCache\Imaging\Processing\SaveOptionsFactory
        calls:
            - [setQuality, ['%save_options.quality%']]
    save_options_configurator:
        class: Strider2038\ImgCache\Imaging\Parsing\SaveOptionsConfigurator
    image_processor:
        class: Strider2038\ImgCache\Imaging\Processing\ImageProcessor
        arguments:
            - '@imagick_transformer_factory'
            - '@image_factory'
        calls:
            - [setLogger, ['@logger']]
    imagick_transformer_factory:
        class: Strider2038\ImgCache\Imaging\Processing\Imagick\ImagickTransformerFactory
        arguments:
            - '@file_operations'
            - '@stream_factory'

    # imaging/transformation
    transformations_creator:
        class: Strider2038\ImgCache\Imaging\Transformation\TransformationCreator
        arguments:
            - '@transformation_factory_flyweight'
    transformation_factory_flyweight:
        class: Strider2038\ImgCache\Imaging\Transformation\TransformationFactoryFlyweight

    # imaging/source
    direct_key_mapper:
        class: Strider2038\ImgCache\Imaging\Storage\Data\DirectKeyMapper

    # imaging/validation
    image_validator:
        class: Strider2038\ImgCache\Imaging\Validation\ImageValidator
    key_validator:
        class: Strider2038\ImgCache\Imaging\Validation\KeyValidator

    violations_formatter:
        class: Strider2038\ImgCache\Imaging\Validation\ViolationFormatter
