services:
    router:
        class: Strider2038\ImgCache\Service\Router
        arguments:
            - '@image_validator'
            - '@url_route_detector'
        calls:
            - [setLogger, ['@logger']]

    url_route_detector:
        class: Strider2038\ImgCache\Service\Routing\UrlRouteDetector
        arguments:
            - '@routing_paths'

    routing_path_factory:
        class: Strider2038\ImgCache\Service\Routing\RoutingPathFactory
        arguments:
            - '@model_validator'
            - '@violations_formatter'

    routing_paths:
        factory:
            - '@routing_path_factory'
            - 'createRoutingPathCollection'
        arguments:
            - '%routing_map%'
