services:
    logger_factory:
        class: Strider2038\ImgCache\Utility\LoggerFactory
        arguments:
            - '%application.start_up_time%'
            - '%log.directory%'

    logger:
        factory:
            - '@logger_factory'
            - 'createLogger'
        arguments:
            - '%log.name%'
            - '%log.level%'

    client_request_logger:
        class: Strider2038\ImgCache\Utility\ClientRequestLogger
        arguments:
            - '@logger'
            - '%server_configuration%'

    guzzle_handler_stack_factory:
        class: Strider2038\ImgCache\Utility\GuzzleHandlerStackFactory
        arguments:
            - '@logger'

    guzzle_logger_handler_stack:
        factory:
            - '@guzzle_handler_stack_factory'
            - 'createLoggerStack'

    guzzle_client_factory:
        class: Strider2038\ImgCache\Utility\GuzzleClientFactory
        arguments:
            - '@stream_factory'
            - '@guzzle_logger_handler_stack'

    metadata_reader:
        class: Strider2038\ImgCache\Utility\MetadataReader

    entity_validator:
        class: Strider2038\ImgCache\Utility\EntityValidator
        arguments:
            - '@constraint_validator_factory'
            - '@violation_formatter'
    violation_formatter:
        class: Strider2038\ImgCache\Utility\ViolationFormatter
    constraint_validator_factory:
        class: Strider2038\ImgCache\Utility\Validation\CustomConstraintValidatorFactory
        arguments:
            - '@metadata_reader'
