services:
    logger_factory:
        class: Strider2038\ImgCache\Utility\LoggerFactory
        arguments:
            - '%log.directory%'

    logger:
        factory:
            - '@logger_factory'
            - 'createLogger'
        arguments:
            - '%log.name%'
            - '%log.level%'

    request_logger:
        class: Strider2038\ImgCache\Utility\RequestLogger
        arguments:
            - '@logger'
            - '%server_configuration%'

    guzzle_handler_stack_factory:
        class: Strider2038\ImgCache\Utility\GuzzleHandlerStackFactory
        arguments:
            - '@logger'

    guzzle_logger_handler_stack:
        factory:
            - '@guzzle_handler_stack_factory'
            - 'createLoggerStack'
