parameters:
    yandex_disk_client.token: ''
    yandex_disk_client.parameters:
        base_uri: 'https://webdav.yandex.ru/v1'
        headers:
            Authorization: 'OAuth %yandex_disk_client.token%'
            Host: 'webdav.yandex.ru'
            User-Agent: 'Image Caching Microservice'
            Accept: '*/*'

services:
    yandex_disk_client:
        class: GuzzleHttp\Client
        arguments:
            - '%yandex_disk_client.parameters%'
    yandex_disk_client_adapter:
        class: Strider2038\ImgCache\Utility\GuzzleClientAdapter
        arguments:
            - '@yandex_disk_client'
            - '@stream_factory'

    # controller
    yandex_disk_cache_image_controller:
        class: Strider2038\ImgCache\Service\ImageController
        arguments:
            - '@response_factory'
            - '@yandex_disk_cache_action_factory'
            - '@security'
    yandex_disk_cache_action_factory:
        class: Strider2038\ImgCache\Service\Image\ImageActionFactory
        arguments:
            - '@yandex_disk_cache_action_get'
            - '@yandex_disk_cache_action_create'
            - '@yandex_disk_cache_action_replace'
            - '@yandex_disk_cache_action_delete'
    yandex_disk_cache_action_get:
        class: Strider2038\ImgCache\Service\Image\GetAction
        arguments:
            - '@response_factory'
            - '@image_filename_factory'
            - '@yandex_disk_image_storage'
            - '@yandex_disk_image_cache'
    yandex_disk_cache_action_create:
        class: Strider2038\ImgCache\Service\Image\CreateAction
        arguments:
            - '@response_factory'
            - '@image_filename_factory'
            - '@yandex_disk_image_storage'
            - '@image_factory'
    yandex_disk_cache_action_replace:
        class: Strider2038\ImgCache\Service\Image\ReplaceAction
        arguments:
            - '@response_factory'
            - '@image_filename_factory'
            - '@yandex_disk_image_storage'
            - '@yandex_disk_image_cache'
            - '@image_factory'
    yandex_disk_cache_action_delete:
        class: Strider2038\ImgCache\Service\Image\DeleteAction
        arguments:
            - '@response_factory'
            - '@image_filename_factory'
            - '@yandex_disk_image_storage'
            - '@yandex_disk_image_cache'

    yandex_disk_image_storage:
        class: Strider2038\ImgCache\Imaging\ImageStorage
        arguments:
            - '@yandex_disk_image_extractor'
            - '@yandex_disk_image_writer'

    yandex_disk_image_cache_web_directory:
        factory:
            - '@directory_name_factory'
            - 'createDirectoryName'
        arguments:
            - '%yandex_disk_image_cache.base_directory%'
            - 'true'

    yandex_disk_image_cache:
        class: Strider2038\ImgCache\Imaging\ImageCache
        arguments:
            - '@yandex_disk_image_cache_web_directory'
            - '@file_operations'
            - '@image_processor'

    yandex_disk_image_extractor:
        class: Strider2038\ImgCache\Imaging\Extraction\ThumbnailImageExtractor
        arguments:
            - '@thumbnail_key_parser'
            - '@yandex_disk_storage_accessor'
            - '@image_processor'

    yandex_disk_image_writer:
        class: Strider2038\ImgCache\Imaging\Insertion\ThumbnailImageWriter
        arguments:
            - '@thumbnail_key_parser'
            - '@yandex_disk_storage_accessor'

    yandex_disk_storage_accessor:
        class: Strider2038\ImgCache\Imaging\Storage\Accessor\FilesystemStorageAccessor
        arguments:
            - '@yandex_disk_storage_driver'
            - '@image_factory'
            - '@direct_key_mapper'
        calls:
            - [setLogger, ['@logger']]

    yandex_disk_storage_driver:
        class: Strider2038\ImgCache\Imaging\Storage\Driver\WebDAVStorageDriver
        arguments:
            - '%yandex_disk_storage_driver.base_directory%'
            - '@yandex_disk_resource_manipulator'
            - '@yandex_disk_resource_checker'

    yandex_disk_resource_manipulator:
        class: Strider2038\ImgCache\Imaging\Storage\Driver\WebDAV\ResourceManipulator
        arguments:
            - '@yandex_disk_client_adapter'
            - '@yandex_disk_request_options_factory'
    yandex_disk_request_options_factory:
        class: Strider2038\ImgCache\Imaging\Storage\Driver\WebDAV\RequestOptionsFactory
        arguments:
            - '@metadata_reader'
    yandex_disk_resource_checker:
        class: Strider2038\ImgCache\Imaging\Storage\Driver\WebDAV\ResourceChecker
        arguments:
            - '@yandex_disk_resource_properties_getter'
    yandex_disk_resource_properties_getter:
        class: Strider2038\ImgCache\Imaging\Storage\Driver\WebDAV\ResourcePropertiesGetter
        arguments:
            - '@yandex_disk_client_adapter'
            - '@yandex_disk_response_parser'
    yandex_disk_response_parser:
        class: Strider2038\ImgCache\Imaging\Storage\Driver\WebDAV\XmlResponseParser
