language: php

php:
  - '7.1'

sudo: enabled

dist: xenial

install:
  - printf "\n" | pecl install imagick
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml

after_success:
  - travis_retry ./vendor/bin/coveralls -v
