language: php

php:
  - '7.1'

sudo: enabled

dist: xenial

before_install:
  - sudo apt update
  - sudo apt-add-repository -y ppa:ondrej/php

install:
  - sudo apt install -y php-imagick
  - composer install

script:
  - ./vendor/bin/phpunit