FROM strider2038:imgcache-service
MAINTAINER Igor Lazarev <strider2038@rambler.ru>

COPY ./.docker/nginx/service-test.conf /etc/nginx/conf.d/service-test.conf
COPY ./.docker/composer/auth.json /var/run/composer/auth.json

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    composer install

EXPOSE 80 8080
