FROM strider2038:imgcache-service
MAINTAINER Igor Lazarev <strider2038@rambler.ru>

COPY ./.docker/composer/auth.json /var/run/composer/auth.json

RUN apk add --update \
    openssh \
    nano \
    iputils && \
    pecl install xdebug && \
    docker-php-ext-enable xdebug && \
    mkdir -p /var/log/xdebug && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    composer install

COPY ./.docker/supervisor/sshd.conf /etc/supervisord/sshd.conf
COPY ./.docker/composer/auth.json /var/run/composer/auth.json
COPY ./.docker/php/* /usr/local/etc/php/conf.d/
COPY ./.docker/sshd/* /etc/ssh/
COPY ./.docker/env/dev.sh /etc/profile.d/dev.sh

RUN chmod 600 /etc/ssh/ssh_host_*

EXPOSE 22 80 9001
