FROM strider2038:imgcache-service
MAINTAINER Igor Lazarev <strider2038@rambler.ru>

ENV XDEBUG_CONFIG="remote_enable=1 remote_mode=req remote_port=9001 remote_host=172.17.0.1 remote_log=/var/log/xdebug/remote.log"
ENV PHP_IDE_CONFIG="serverName=default"

COPY ./.docker/composer/auth.json /var/run/composer/auth.json

RUN apk add --update \
    nano \
    iputils && \
    pecl install xdebug && \
    docker-php-ext-enable xdebug && \
    mkdir -p /var/log/xdebug && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    composer install

COPY ./.docker/composer/auth.json /var/run/composer/auth.json
COPY ./.docker/php/* /usr/local/etc/php/conf.d/
COPY ./.docker/env/aliases.sh /etc/profile.d/aliases.sh

EXPOSE 80 9001
