FROM strider2038:imgcache-service
MAINTAINER Igor Lazarev <strider2038@rambler.ru>

COPY ./conf/php/* /usr/local/etc/php/conf.d/

RUN apk add --update \
    nano \
    iputils \
    autoconf \
    g++ \
    make && \
    pecl install xdebug && \
    docker-php-ext-enable xdebug

EXPOSE 80 9001

VOLUME /services/imgcache
