imports:
    - { resource: 'services/configuration.yml' }
    - { resource: 'services/utilities.yml' }

services:
    configuration_loader:
        class: Strider2038\ImgCache\Configuration\ConfigurationLoader
        arguments:
            - '@configuration_file_parser'
            - '@configuration_processor'
            - '@configuration_factory'
