imports:
  - { resource: 'main.yml' }

services:
    logger:
        class: Psr\Log\NullLogger

parameters:
    server_configuration:
        - ~
    web_directory: '%application.directory%/runtime/tests/web'
