imports:
    - { resource: 'services/core.yml' }
    - { resource: 'services/imaging.yml' }
    - { resource: 'services/utilities.yml' }
    - { resource: 'services/yandex-disk-storage.yml' }

parameters:
    yandex_disk_image_cache.base_directory: '%test.web_directory%'
    yandex_disk_storage_driver.base_directory: '%test.storage_root_directory%'

services:
    logger:
        class: Psr\Log\NullLogger
    security:
        class: Strider2038\ImgCache\Core\NullSecurity
