imports:
    - { resource: 'services/core.yml' }
    - { resource: 'services/imaging.yml' }
    - { resource: 'services/yandex-map-storage.yml' }

parameters:
    yandex_map_image_cache.base_directory: '%test.web_directory%'

services:
    logger:
        class: Psr\Log\NullLogger
    security:
        class: Strider2038\ImgCache\Core\NullSecurity
