imports:
  - { resource: 'services/core.yml' }
  - { resource: 'services/configuration.yml' }
  - { resource: 'services/utilities.yml' }
  - { resource: 'services/imaging.yml' }
  - { resource: 'services/request-handling.yml' }
  - { resource: 'services/image-cache.yml' }
  - { resource: 'services/parameters.yml' }
  - { resource: 'local.yml', ignore_errors: true }
