parameters:
  app.debug: true
  security.accessToken: 'sample-security-token-must-be-replaced-with-real'
  log.directory: '%app.directory%/runtime'
  log.name: 'app.log'
  log.level: 100
  saveOptions.quality: 90
  imageCache.baseDirectory: '%app.directory%/web/i'
  filesystemSource.baseDirectory: '%app.directory%/tests/assets'
  routes:
    /i: 'imageController'

services:
  # external
  filesystem:
    class: \Symfony\Component\Filesystem\Filesystem

  # core components
  request:
    class: \Strider2038\ImgCache\Core\Request
  security:
    class: \Strider2038\ImgCache\Core\Security
    arguments: ['@request', '%security.accessToken%']
  loggerFactory:
    class: \Strider2038\ImgCache\Core\LoggerFactory
    arguments: ['%log.directory%']
  logger:
    factory: ['@loggerFactory', 'createLogger']
    arguments: ['%log.name%', '%log.level%']
  fileOperations:
    class: \Strider2038\ImgCache\Core\FileOperations
    arguments: ['@filesystem']
    calls:
      - [setLogger, ['@logger']]

  # routing components
  router:
    class: \Strider2038\ImgCache\Service\Router
    arguments: ['@imageValidator', '%routes%']
    calls:
      - [setLogger, ['@logger']]

  # controllers
  imageController:
    class: \Strider2038\ImgCache\Service\ImageController
    arguments: ['@security', '@imageCache', '@request']

  # imaging
  imageCache:
    class: \Strider2038\ImgCache\Imaging\ImageCache
    arguments: ['%imageCache.baseDirectory%', '@fileOperations', '@imageFactory', '@thumbnailImageExtractor']

  # imaging/image
  imageFactory:
    class: \Strider2038\ImgCache\Imaging\Image\ImageFactory
    arguments: ['@saveOptionsFactory', '@imageValidator', '@fileOperations']

  # imaging/extraction
  thumbnailImageExtractor:
    class: \Strider2038\ImgCache\Imaging\Extraction\ThumbnailImageExtractor
    arguments: ['@thumbnailKeyParser', '@filesystemSourceAccessor', '@thumbnailProcessingConfigurationParser', '@imageProcessor']

  # imaging/parsing
  thumbnailKeyParser:
    class: \Strider2038\ImgCache\Imaging\Parsing\Thumbnail\ThumbnailKeyParser
    arguments: ['@keyValidator', '@imageValidator']
  thumbnailProcessingConfigurationParser:
    class: \Strider2038\ImgCache\Imaging\Parsing\Processing\ThumbnailProcessingConfigurationParser
    arguments: ['@transformationsCreator', '@saveOptionsFactory', '@saveOptionsConfigurator']

  # imaging/processing
  saveOptionsFactory:
    class: \Strider2038\ImgCache\Imaging\Processing\SaveOptionsFactory
    calls:
      - [setQuality, ['%saveOptions.quality%']]
  saveOptionsConfigurator:
    class: \Strider2038\ImgCache\Imaging\Parsing\SaveOptionsConfigurator
  imageProcessor:
    class: \Strider2038\ImgCache\Imaging\Processing\ImageProcessor
    arguments: ['@imagickEngine']
  imagickEngine:
    class: \Strider2038\ImgCache\Imaging\Processing\Adapter\ImagickEngine
    arguments: ['@fileOperations']
    calls:
      - [setLogger, ['@logger']]

  # imaging/transformation
  transformationsCreator:
    class: \Strider2038\ImgCache\Imaging\Transformation\TransformationsCreator
    arguments: ['@transformationFactoryFlyweight']
  transformationFactoryFlyweight:
    class: \Strider2038\ImgCache\Imaging\Transformation\TransformationFactoryFlyweight

  # imaging/source
  filesystemSourceAccessor:
    class: \Strider2038\ImgCache\Imaging\Source\Accessor\FilesystemSourceAccessor
    arguments: ['@filesystemSource', '@directKeyMapper']
    calls:
      - [setLogger, ['@logger']]
  filesystemSource:
    class: \Strider2038\ImgCache\Imaging\Source\FilesystemSource
    arguments: ['%filesystemSource.baseDirectory%', '@fileOperations', '@imageFactory']
  directKeyMapper:
    class: \Strider2038\ImgCache\Imaging\Source\Mapping\DirectKeyMapper

  # imaging/validation
  imageValidator:
    class: \Strider2038\ImgCache\Imaging\Validation\ImageValidator
  keyValidator:
    class: \Strider2038\ImgCache\Imaging\Validation\KeyValidator
