parameters:
  app.debug: true
  security.access_token: 'sample-security-token-must-be-replaced-with-real'
  log.directory: '%app.directory%/runtime'
  log.name: 'app.log'
  log.level: 100
  save_options.quality: 90
  image_cache.base_directory: '%app.directory%/web/i'
  filesystem_source.base_directory: '%app.directory%/tests/assets'
  routes:
    /i: 'image_controller'

services:
  # external
  filesystem:
    class: \Symfony\Component\Filesystem\Filesystem

  # core components
  request_factory:
    class: \Strider2038\ImgCache\Core\Http\RequestFactory
  request:
    factory: ['@request_factory', 'createRequest']
    arguments: ['%server_configuration%']
  response_sender:
    class: \Strider2038\ImgCache\Core\Http\ResponseSender
  response_factory:
    class: \Strider2038\ImgCache\Core\Http\ResponseFactory
    arguments: ['@request', '%app.debug%']
  security:
    class: \Strider2038\ImgCache\Core\Security
    arguments: ['@request', '%security.access_token%']
  logger_factory:
    class: \Strider2038\ImgCache\Core\LoggerFactory
    arguments: ['%log.directory%']
  logger:
    factory: ['@logger_factory', 'createLogger']
    arguments: ['%log.name%', '%log.level%']
  file_operations:
    class: \Strider2038\ImgCache\Core\FileOperations
    arguments: ['@filesystem']
    calls:
      - [setLogger, ['@logger']]

  # routing components
  router:
    class: \Strider2038\ImgCache\Service\Router
    arguments: ['@image_validator', '%routes%']
    calls:
      - [setLogger, ['@logger']]

  # controllers
  image_controller:
    class: \Strider2038\ImgCache\Service\ImageController
    arguments:
      - '@response_factory'
      - '@security'
      - '@image_cache'
      - '@request'

  # imaging
  image_cache:
    class: \Strider2038\ImgCache\Imaging\ImageCache
    arguments:
      - '%image_cache.base_directory%'
      - '@file_operations'
      - '@image_factory'
      - '@thumbnail_image_extractor'

  # imaging/image
  image_factory:
    class: \Strider2038\ImgCache\Imaging\Image\ImageFactory
    arguments:
      - '@save_options_factory'
      - '@image_validator'
      - '@file_operations'

  # imaging/extraction
  thumbnail_image_extractor:
    class: \Strider2038\ImgCache\Imaging\Extraction\ThumbnailImageExtractor
    arguments:
      - '@thumbnail_key_parser'
      - '@filesystem_source_accessor'
      - '@image_processor'

  # imaging/parsing
  thumbnail_key_parser:
    class: \Strider2038\ImgCache\Imaging\Parsing\Thumbnail\ThumbnailKeyParser
    arguments:
      - '@key_validator'
      - '@image_validator'
      - '@thumbnail_processing_configuration_parser'
  thumbnail_processing_configuration_parser:
    class: \Strider2038\ImgCache\Imaging\Parsing\Processing\ThumbnailProcessingConfigurationParser
    arguments:
      - '@transformations_creator'
      - '@save_options_factory'
      - '@save_options_configurator'

  # imaging/processing
  save_options_factory:
    class: \Strider2038\ImgCache\Imaging\Processing\SaveOptionsFactory
    calls:
      - [setQuality, ['%save_options.quality%']]
  save_options_configurator:
    class: \Strider2038\ImgCache\Imaging\Parsing\SaveOptionsConfigurator
  image_processor:
    class: \Strider2038\ImgCache\Imaging\Processing\ImageProcessor
    arguments: ['@imagick_engine']
  imagick_engine:
    class: \Strider2038\ImgCache\Imaging\Processing\Adapter\ImagickEngine
    arguments: ['@file_operations']
    calls:
      - [setLogger, ['@logger']]

  # imaging/transformation
  transformations_creator:
    class: \Strider2038\ImgCache\Imaging\Transformation\TransformationsCreator
    arguments: ['@transformation_factory_flyweight']
  transformation_factory_flyweight:
    class: \Strider2038\ImgCache\Imaging\Transformation\TransformationFactoryFlyweight

  # imaging/source
  filesystem_source_accessor:
    class: \Strider2038\ImgCache\Imaging\Source\Accessor\FilesystemSourceAccessor
    arguments:
      - '@filesystem_source'
      - '@direct_key_mapper'
    calls:
      - [setLogger, ['@logger']]
  filesystem_source:
    class: \Strider2038\ImgCache\Imaging\Source\FilesystemSource
    arguments:
      - '%filesystem_source.base_directory%'
      - '@file_operations'
      - '@image_factory'
  direct_key_mapper:
    class: \Strider2038\ImgCache\Imaging\Source\Mapping\DirectKeyMapper

  # imaging/validation
  image_validator:
    class: \Strider2038\ImgCache\Imaging\Validation\ImageValidator
  key_validator:
    class: \Strider2038\ImgCache\Imaging\Validation\KeyValidator
