imports:
  - { resource: 'parameters.yml' }
  - { resource: 'services/core.yml' }
  - { resource: 'services/security.yml' }
  - { resource: 'services/utilities.yml' }
  - { resource: 'services/routing.yml' }
  - { resource: 'services/imaging.yml' }
  - { resource: 'services/filesystem-storage.yml' }
  - { resource: 'services/yandex-map-storage.yml' }
