@startuml

Application -> RequestHandler : handleRequest(request)

RequestHandler -> AccessControl : canHandleRequest(request)
RequestHandler <-- AccessControl : false

RequestHandler -> ResponseFactory : createTextResponse(403, 'Access denied')
RequestHandler <-- ResponseFactory : response

Application <-- RequestHandler : response
Application -> ResponseSender : sendResponse(response)

@enduml
