@startuml

ImageStorage -> SourceImageExtractor: getProcessedImage('/image.jpg')
SourceImageExtractor -> FilesystemStorageAccessor: getImage('/image.jpg')
FilesystemStorageAccessor -> FilesystemStorageDriver: getData('/filesource/image.jpg')
FilesystemStorageAccessor <-- FilesystemStorageDriver: StreamInterface
SourceImageExtractor <-- FilesystemStorageAccessor: Image
ImageStorage <-- SourceImageExtractor: Image

@enduml
