@startuml

ImageStorage -> ThumbnailImageExtractor: getProcessedImage('/image_s100x80.jpg')
ThumbnailImageExtractor -> FilesystemStorageAccessor: getImage('/image.jpg')
FilesystemStorageAccessor -> FilesystemStorageDriver: getData('/filesource/image.jpg')
FilesystemStorageAccessor <-- FilesystemStorageDriver: StreamInterface
ThumbnailImageExtractor <-- FilesystemStorageAccessor: Image
ThumbnailImageExtractor -> ThumbnailImageCreator: createThumbnailImageByConfiguration(Image, 's100x80')
ThumbnailImageExtractor <-- ThumbnailImageCreator: Image
ImageStorage <-- ThumbnailImageExtractor: Image

@enduml
